categories = [
    {"Connecting Word": "Super___", "Words": ["man", "power", "human", "strength"]},
    {"Connecting Word": "Play___", "Words": ["ground", "park", "boy", "game"]},
    {"Connecting Word": "Animals", "Words": ["cat", "dog", "elephant", "lion"]},
    {"Connecting Word": "Colors", "Words": ["red", "blue", "green", "yellow"]},
    {"Connecting Word": "Fruits", "Words": ["apple", "banana", "orange", "strawberry"]},
    {"Connecting Word": "Countries", "Words": ["USA", "China", "India", "Brazil"]},
    {"Connecting Word": "Art", "Words": ["painting", "sculpture", "drawing", "photography"]},
    {"Connecting Word": "Music", "Words": ["piano", "guitar", "violin", "drums"]},
    {"Connecting Word": "Science", "Words": ["chemistry", "biology", "physics", "astronomy"]},
    {"Connecting Word": "Tech", "Words": ["computer", "software", "internet", "smartphone"]},
    {"Connecting Word": "Food", "Words": ["pizza", "burger", "sushi", "pasta"]},
    {"Connecting Word": "Nature", "Words": ["tree", "flower", "mountain", "river"]},
    {"Connecting Word": "Jobs", "Words": ["teacher", "doctor", "engineer", "artist"]},
    {"Connecting Word": "Sports", "Words": ["football", "basketball", "soccer", "tennis"]},
    {"Connecting Word": "Clothing", "Words": ["shirt", "pants", "dress", "jacket"]},
    {"Connecting Word": "Transportation", "Words": ["car", "train", "bicycle", "plane"]},
    {"Connecting Word": "Weather", "Words": ["sun", "rain", "snow", "wind"]},
    {"Connecting Word": "Emotions", "Words": ["happy", "sad", "angry", "excited"]},
    {"Connecting Word": "Hobbies", "Words": ["reading", "painting", "gardening", "cooking"]},
    {"Connecting Word": "School Subjects", "Words": ["math", "science", "history", "english"]},
    {"Connecting Word": "Furniture", "Words": ["table", "chair", "bed", "sofa"]},
    {"Connecting Word": "Shapes", "Words": ["circle", "square", "triangle", "rectangle"]},
    {"Connecting Word": "Planets", "Words": ["Mercury", "Venus", "Earth", "Mars"]},
    {"Connecting Word": "Languages", "Words": ["English", "Spanish", "French", "Chinese"]},
    {"Connecting Word": "Movies", "Words": ["action", "comedy", "drama", "horror"]},
    {"Connecting Word": "Books", "Words": ["fiction", "non-fiction", "fantasy", "mystery"]},
    {"Connecting Word": "Games", "Words": ["video", "board", "card", "role-playing"]},
    {"Connecting Word": "Musical Instruments", "Words": ["trumpet", "flute", "clarinet", "saxophone"]},
    {"Connecting Word": "Professions", "Words": ["lawyer", "architect", "chef", "pilot"]},
    {"Connecting Word": "Desserts", "Words": ["cake", "ice cream", "pie", "pudding"]},
    {"Connecting Word": "Vegetables", "Words": ["carrot", "broccoli", "potato", "tomato"]},
    {"Connecting Word": "Body Parts", "Words": ["head", "shoulder", "knee", "toe"]},
    {"Connecting Word": "Continents", "Words": ["North America", "South America", "Europe", "Asia"]},
    {"Connecting Word": "Planets", "Words": ["Jupiter", "Saturn", "Uranus", "Neptune"]},
    {"Connecting Word": "Elements", "Words": ["fire", "water", "earth", "air"]},
    {"Connecting Word": "Clothing Accessories", "Words": ["hat", "scarf", "gloves", "sunglasses"]}
]