categories = [
    {"Connecting Word": "Weapons", "Words": ["AssaultRifle", "Shotgun", "SniperRifle", "Pistol"]},
    {"Connecting Word": "Places", "Words": ["TiltedTowers", "PleasantPark", "LazyLake", "RetailRow"]},
    {"Connecting Word": "Builds", "Words": ["Wood", "Stone", "Metal", "Brick"]},
    {"Connecting Word": "Heals", "Words": ["Bandages", "ShieldPotion", "MedKit", "SlurpJuice"]},
    {"Connecting Word": "Outfits", "Words": ["RenegadeRaider", "SkullTrooper", "BlackKnight", "Fishstick"]},
    {"Connecting Word": "Rides", "Words": ["ShoppingCart", "ATK", "Motorboat", "Choppa"]},
    {"Connecting Word": "Modes", "Words": ["Solo", "Duo", "Squad", "TeamRumble"]},
    {"Connecting Word": "Events", "Words": ["LiveConcert", "SeasonLaunch", "HolidayEvent", "InGameTournament"]},
    {"Connecting Word": "Traps", "Words": ["SpikeTrap", "Bouncer", "LaunchPad", "CozyCampfire"]},
    {"Connecting Word": "Emotes", "Words": ["DanceMoves", "Wave", "Floss", "Tidy"]},
    {"Connecting Word": "Loot", "Words": ["TreasureChest", "SupplyDrop", "AmmoBox", "LootLlama"]},
    {"Connecting Word": "Structures", "Words": ["Ramp", "Wall", "Floor", "Roof"]},
    {"Connecting Word": "Mobility", "Words": ["Grappler", "ShockwaveGrenade", "BouncePad", "RiftToGo"]},
    {"Connecting Word": "NPCs", "Words": ["Fisherman", "Hunter", "Warrior", "Trader"]},
    {"Connecting Word": "Cosmetics", "Words": ["Glider", "Pickaxe", "BackBling", "Emote"]},
    {"Connecting Word": "Currency", "Words": ["VBucks", "GoldBars", "SilverCoins", "CopperPennies"]},
]